### ISSUE TITLE
Building the WebRTC lib for Windows

### ISSUE THREAD

**Issue by daveime** [ipop-project/ipop-project.github.io#22]
What do I have to do to get this damn thing working on Window 7 x64?

I keep running into WindowsError: [Error 5] Access is denied Python messages during the "fetch --nohooks webrtc" step. I verified that my PATH is correct, I'm running the CMD window as admin, I've disabled both my antivirus and Windows Search to prevent files / directories getting locked in any way from advice I've seen on other threads about this issue.

And still the same messages. I wouldn't mind but they just seem to be temporary directories created during the download process, but because of some really shitty exception handling in Python, it croaks the entire process even though the src is probably good - meaning later elements he downloads such as the gn.exe etc never get done.

What exactly is locking these files and preventing the fetch process from completing?

```
C:\Users\Dave\webrtc-checkout>fetch --nohooks webrtc
Running: 'C:\Users\Dave\Downloads\depot_tools\python276_bin\python.exe' 'C:\Users\Dave\Downloads\depot_tools\gclient.py' root
Running: 'C:\Users\Dave\Downloads\depot_tools\python276_bin\python.exe' 'C:\Users\Dave\Downloads\depot_tools\gclient.py' config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/external/webrtc.git",
    "managed": False,
    "name": "src",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: 'C:\Users\Dave\Downloads\depot_tools\python276_bin\python.exe' 'C:\Users\Dave\Downloads\depot_tools\gclient.py' sync --nohooks --with_branch_heads
c:\users\dave\webrtc-checkout\_gclient_src_o4zufa\GIT~1 - The directory is not empty.

src (ERROR)
----------------------------------------
[0:00:00] Started.
[0:00:00]

________ running 'git -c core.deltaBaseCacheLimit=512m clone --no-checkout --progress https://chromium.googlesource.com/external/webrtc.git C:\Users\Dave\webrtc
-checkout\_gclient_src_o4zufa' in 'C:\Users\Dave\webrtc-checkout'
[0:00:00] Cloning into 'C:\Users\Dave\webrtc-checkout\_gclient_src_o4zufa'...
[0:00:01] remote: Sending approximately 141.59 MiB ...
[0:00:01] remote: Counting objects: 1
[0:00:01] remote: Counting objects: 5187, done
[0:00:01] remote: Finding sources:   1% (2/174)
[0:00:01] remote: Finding sources:  10% (18/174)
[0:00:01] remote: Finding sources: 100% (174/174)
[0:00:01] Receiving objects:   0% (1/196847)
[0:00:03] Receiving objects:   0% (1029/196847), 771.77 KiB | 432.00 KiB/s
[0:00:04] Receiving objects:   1% (2090/196847), 1.25 MiB | 417.00 KiB/s
[0:00:06] Receiving objects:   2% (3937/196847), 1.82 MiB | 439.00 KiB/s
[0:00:07] Receiving objects:   3% (5906/196847), 2.75 MiB | 487.00 KiB/s
[0:00:08] Receiving objects:   3% (7474/196847), 3.38 MiB | 522.00 KiB/s
[0:00:09] Receiving objects:   4% (9069/196847), 4.00 MiB | 574.00 KiB/s
[0:00:11] Receiving objects:   5% (11753/196847), 4.94 MiB | 563.00 KiB/s
[0:00:12] Receiving objects:   7% (13780/196847), 5.56 MiB | 564.00 KiB/s
[0:00:13] Receiving objects:   8% (15748/196847), 6.19 MiB | 569.00 KiB/s
[0:00:15] Receiving objects:  10% (19685/196847), 7.13 MiB | 563.00 KiB/s
[0:00:16] Receiving objects:  12% (23622/196847), 7.75 MiB | 602.00 KiB/s
[0:00:17] Receiving objects:  13% (27282/196847), 8.38 MiB | 601.00 KiB/s
[0:00:18] Receiving objects:  15% (30303/196847), 9.00 MiB | 600.00 KiB/s
[0:00:19] Receiving objects:  17% (33464/196847), 9.63 MiB | 604.00 KiB/s
[0:00:21] Receiving objects:  18% (37262/196847), 10.50 MiB | 573.00 KiB/s
[0:00:23] Receiving objects:  20% (39370/196847), 10.94 MiB | 470.00 KiB/s
[0:00:24] Receiving objects:  21% (41338/196847), 11.31 MiB | 409.00 KiB/s
[0:00:25] Receiving objects:  21% (43258/196847), 11.71 MiB | 347.00 KiB/s
[0:00:26] Receiving objects:  22% (44758/196847), 12.19 MiB | 331.00 KiB/s
[0:00:27] Receiving objects:  24% (47244/196847), 12.69 MiB | 380.00 KiB/s
[0:00:29] Receiving objects:  26% (51181/196847), 13.62 MiB | 459.00 KiB/s
[0:00:30] Receiving objects:  27% (54926/196847), 14.25 MiB | 522.00 KiB/s
[0:00:31] Receiving objects:  30% (59055/196847), 15.19 MiB | 598.00 KiB/s
[0:00:32] Receiving objects:  34% (66928/196847), 15.81 MiB | 604.00 KiB/s
[0:00:34] Receiving objects:  38% (74802/196847), 16.44 MiB | 605.00 KiB/s
[0:00:35] Receiving objects:  42% (82676/196847), 17.06 MiB | 611.00 KiB/s
[0:00:36] Receiving objects:  46% (90550/196847), 17.69 MiB | 611.00 KiB/s
[0:00:37] Receiving objects:  50% (99606/196847), 18.50 MiB | 578.00 KiB/s
[0:00:38] Receiving objects:  54% (108024/196847), 19.12 MiB | 579.00 KiB/s
[0:00:39] Receiving objects:  56% (111520/196847), 19.75 MiB | 579.00 KiB/s
[0:00:40] Receiving objects:  56% (111520/196847), 20.37 MiB | 579.00 KiB/s
[0:00:41] Receiving objects:  56% (111520/196847), 21.00 MiB | 579.00 KiB/s
[0:00:42] Receiving objects:  56% (111520/196847), 21.62 MiB | 612.00 KiB/s
[0:00:44] Receiving objects:  56% (111522/196847), 22.87 MiB | 612.00 KiB/s
[0:00:46] Receiving objects:  56% (111522/196847), 23.50 MiB | 612.00 KiB/s
[0:00:47] Receiving objects:  56% (111522/196847), 24.12 MiB | 612.00 KiB/s
[0:00:48] Receiving objects:  56% (111522/196847), 24.62 MiB | 579.00 KiB/s
[0:00:49] Receiving objects:  56% (111523/196847), 25.56 MiB | 579.00 KiB/s
[0:00:50] Receiving objects:  56% (111523/196847), 26.18 MiB | 579.00 KiB/s
[0:00:51] Receiving objects:  56% (111523/196847), 26.81 MiB | 578.00 KiB/s
[0:00:52] Receiving objects:  56% (111523/196847), 27.43 MiB | 610.00 KiB/s
[0:00:54] Receiving objects:  56% (111524/196847), 28.68 MiB | 608.00 KiB/s
[0:00:56] Receiving objects:  56% (111524/196847), 29.31 MiB | 609.00 KiB/s
[0:00:57] Receiving objects:  56% (111525/196847), 29.93 MiB | 610.00 KiB/s
[0:00:58] Receiving objects:  56% (111529/196847), 30.56 MiB | 576.00 KiB/s
[0:01:00] Receiving objects:  56% (111530/196847), 31.18 MiB | 502.00 KiB/s
[0:01:01] Receiving objects:  56% (111533/196847), 32.06 MiB | 482.00 KiB/s
[0:01:02] Receiving objects:  56% (111533/196847), 32.62 MiB | 465.00 KiB/s
[0:01:04] Receiving objects:  56% (111541/196847), 33.87 MiB | 560.00 KiB/s
[0:01:06] Receiving objects:  56% (111548/196847), 34.81 MiB | 582.00 KiB/s
[0:01:08] Receiving objects:  57% (113477/196847), 35.93 MiB | 569.00 KiB/s
[0:01:10] Receiving objects:  58% (115288/196847), 36.87 MiB | 568.00 KiB/s
[0:01:11] Receiving objects:  58% (115574/196847), 37.80 MiB | 564.00 KiB/s
[0:01:13] Receiving objects:  59% (116140/196847), 38.43 MiB | 562.00 KiB/s
[0:01:14] Receiving objects:  59% (117408/196847), 39.37 MiB | 604.00 KiB/s
[0:01:16] Receiving objects:  60% (119573/196847), 40.62 MiB | 608.00 KiB/s
[0:01:18] Receiving objects:  61% (121280/196847), 41.55 MiB | 612.00 KiB/s
[0:01:20] Receiving objects:  62% (123351/196847), 42.68 MiB | 583.00 KiB/s
[0:01:21] Receiving objects:  63% (124380/196847), 43.30 MiB | 583.00 KiB/s
[0:01:23] Receiving objects:  63% (125565/196847), 44.55 MiB | 583.00 KiB/s
[0:01:25] Receiving objects:  64% (127864/196847), 45.80 MiB | 613.00 KiB/s
[0:01:27] Receiving objects:  65% (129891/196847), 47.05 MiB | 613.00 KiB/s
[0:01:28] Receiving objects:  66% (130781/196847), 47.68 MiB | 612.00 KiB/s
[0:01:29] Receiving objects:  66% (131226/196847), 47.93 MiB | 578.00 KiB/s
[0:01:30] Receiving objects:  67% (131888/196847), 48.55 MiB | 578.00 KiB/s
[0:01:32] Receiving objects:  67% (132856/196847), 49.80 MiB | 577.00 KiB/s
[0:01:33] Receiving objects:  67% (133605/196847), 50.43 MiB | 578.00 KiB/s
[0:01:35] Receiving objects:  68% (135004/196847), 51.67 MiB | 612.00 KiB/s
[0:01:36] Receiving objects:  69% (135825/196847), 52.30 MiB | 612.00 KiB/s
[0:01:38] Receiving objects:  69% (137622/196847), 53.24 MiB | 612.00 KiB/s
[0:01:39] Receiving objects:  70% (138135/196847), 53.86 MiB | 612.00 KiB/s
[0:01:41] Receiving objects:  71% (139762/196847), 54.92 MiB | 569.00 KiB/s
[0:01:42] Receiving objects:  71% (140806/196847), 55.55 MiB | 569.00 KiB/s
[0:01:43] Receiving objects:  71% (141431/196847), 55.80 MiB | 530.00 KiB/s
[0:01:44] Receiving objects:  72% (142235/196847), 56.24 MiB | 476.00 KiB/s
[0:01:46] Receiving objects:  73% (143699/196847), 56.99 MiB | 454.00 KiB/s
[0:01:47] Receiving objects:  73% (144325/196847), 57.49 MiB | 415.00 KiB/s
[0:01:49] Receiving objects:  73% (145512/196847), 58.74 MiB | 489.00 KiB/s
[0:01:50] Receiving objects:  74% (146066/196847), 59.17 MiB | 493.00 KiB/s
[0:01:52] Receiving objects:  74% (147551/196847), 60.11 MiB | 563.00 KiB/s
[0:01:54] Receiving objects:  75% (149591/196847), 61.36 MiB | 564.00 KiB/s
[0:01:56] Receiving objects:  76% (150993/196847), 62.42 MiB | 550.00 KiB/s
[0:01:57] Receiving objects:  77% (151753/196847), 62.73 MiB | 548.00 KiB/s
[0:01:58] Receiving objects:  77% (152442/196847), 63.30 MiB | 533.00 KiB/s
[0:02:00] Receiving objects:  77% (152831/196847), 63.73 MiB | 395.00 KiB/s
[0:02:02] Receiving objects:  77% (152896/196847), 64.17 MiB | 363.00 KiB/s
[0:02:03] Receiving objects:  78% (153906/196847), 64.73 MiB | 349.00 KiB/s
[0:02:04] Receiving objects:  78% (154286/196847), 65.36 MiB | 333.00 KiB/s
[0:02:06] Receiving objects:  78% (154286/196847), 65.98 MiB | 344.00 KiB/s
[0:02:07] Receiving objects:  78% (154286/196847), 66.61 MiB | 479.00 KiB/s
[0:02:08] Receiving objects:  78% (154286/196847), 67.54 MiB | 539.00 KiB/s
[0:02:09] Receiving objects:  78% (154286/196847), 68.17 MiB | 575.00 KiB/s
[0:02:10] Receiving objects:  78% (154286/196847), 68.79 MiB | 586.00 KiB/s
[0:02:12] Receiving objects:  78% (154286/196847), 69.42 MiB | 581.00 KiB/s
[0:02:13] Receiving objects:  78% (154287/196847), 70.36 MiB | 577.00 KiB/s
[0:02:14] Receiving objects:  78% (154291/196847), 70.67 MiB | 553.00 KiB/s
[0:02:16] Receiving objects:  78% (154292/196847), 71.61 MiB | 558.00 KiB/s
[0:02:17] Receiving objects:  78% (154605/196847), 72.42 MiB | 532.00 KiB/s
[0:02:18] Receiving objects:  79% (155510/196847), 72.92 MiB | 502.00 KiB/s
[0:02:20] Receiving objects:  79% (156655/196847), 73.42 MiB | 480.00 KiB/s
[0:02:22] Receiving objects:  80% (158865/196847), 74.67 MiB | 488.00 KiB/s
[0:02:24] Receiving objects:  81% (160262/196847), 75.92 MiB | 529.00 KiB/s
[0:02:26] Receiving objects:  82% (161415/196847), 76.54 MiB | 558.00 KiB/s
[0:02:27] Receiving objects:  82% (162361/196847), 77.42 MiB | 549.00 KiB/s
[0:02:29] Receiving objects:  82% (163325/196847), 78.17 MiB | 464.00 KiB/s
[0:02:31] Receiving objects:  83% (164161/196847), 78.60 MiB | 352.00 KiB/s
[0:02:33] Receiving objects:  83% (164815/196847), 79.04 MiB | 271.00 KiB/s
[0:02:35] Receiving objects:  84% (165352/196847), 79.48 MiB | 243.00 KiB/s
[0:02:36] Receiving objects:  84% (165954/196847), 79.79 MiB | 240.00 KiB/s
[0:02:38] Receiving objects:  84% (166893/196847), 80.35 MiB | 252.00 KiB/s
[0:02:39] Receiving objects:  85% (167324/196847), 80.60 MiB | 250.00 KiB/s
[0:02:41] Receiving objects:  85% (167981/196847), 80.98 MiB | 244.00 KiB/s
[0:02:42] Receiving objects:  85% (168196/196847), 81.10 MiB | 235.00 KiB/s
[0:02:43] Receiving objects:  85% (168636/196847), 81.35 MiB | 212.00 KiB/s
[0:02:45] Receiving objects:  85% (169180/196847), 81.60 MiB | 169.00 KiB/s
[0:02:46] Receiving objects:  86% (169512/196847), 81.73 MiB | 166.00 KiB/s
[0:02:48] Receiving objects:  86% (170217/196847), 82.10 MiB | 166.00 KiB/s
[0:02:50] Receiving objects:  86% (170854/196847), 82.48 MiB | 181.00 KiB/s
[0:02:51] Receiving objects:  87% (171285/196847), 82.85 MiB | 214.00 KiB/s
[0:02:53] Receiving objects:  87% (172149/196847), 83.29 MiB | 221.00 KiB/s
[0:02:55] Receiving objects:  87% (173011/196847), 83.66 MiB | 234.00 KiB/s
[0:02:56] Receiving objects:  88% (173546/196847), 83.98 MiB | 247.00 KiB/s
[0:02:57] Receiving objects:  88% (173919/196847), 84.29 MiB | 249.00 KiB/s
[0:02:59] Receiving objects:  88% (174528/196847), 84.73 MiB | 250.00 KiB/s
[0:03:00] Receiving objects:  88% (175030/196847), 84.98 MiB | 247.00 KiB/s
[0:03:02] Receiving objects:  89% (175915/196847), 85.48 MiB | 260.00 KiB/s
[0:03:04] Receiving objects:  90% (177163/196847), 86.35 MiB | 353.00 KiB/s
[0:03:05] Receiving objects:  90% (178627/196847), 86.98 MiB | 439.00 KiB/s
[0:03:07] Receiving objects:  91% (180170/196847), 88.10 MiB | 534.00 KiB/s
[0:03:08] Receiving objects:  91% (180548/196847), 88.60 MiB | 512.00 KiB/s
[0:03:10] Receiving objects:  92% (181933/196847), 89.48 MiB | 474.00 KiB/s
[0:03:11] Receiving objects:  92% (182560/196847), 89.73 MiB | 452.00 KiB/s
[0:03:13] Receiving objects:  93% (183068/196847), 90.22 MiB | 425.00 KiB/s
[0:03:14] Receiving objects:  93% (184022/196847), 90.85 MiB | 415.00 KiB/s
[0:03:16] Receiving objects:  94% (185037/196847), 91.54 MiB | 384.00 KiB/s
[0:03:17] Receiving objects:  94% (186665/196847), 92.16 MiB | 406.00 KiB/s
[0:03:18] Receiving objects:  95% (188413/196847), 92.79 MiB | 449.00 KiB/s
[0:03:20] Receiving objects:  96% (190692/196847), 94.04 MiB | 570.00 KiB/s
[0:03:22] Receiving objects:  97% (191226/196847), 94.85 MiB | 559.00 KiB/s
[0:03:23] Receiving objects:  97% (191227/196847), 95.41 MiB | 537.00 KiB/s
[0:03:25] Receiving objects:  97% (191227/196847), 96.35 MiB | 526.00 KiB/s
[0:03:26] Receiving objects:  97% (191227/196847), 96.97 MiB | 524.00 KiB/s
[0:03:27] Receiving objects:  97% (191232/196847), 97.85 MiB | 550.00 KiB/s
[0:03:29] Receiving objects:  97% (191240/196847), 98.78 MiB | 556.00 KiB/s
[0:03:31] Receiving objects:  97% (191248/196847), 100.03 MiB | 566.00 KiB/s
[0:03:33] Receiving objects:  97% (191257/196847), 100.97 MiB | 601.00 KiB/s
[0:03:34] Receiving objects:  97% (191257/196847), 101.91 MiB | 602.00 KiB/s
[0:03:36] Receiving objects:  97% (191258/196847), 102.53 MiB | 596.00 KiB/s
[0:03:37] Receiving objects:  97% (191259/196847), 103.22 MiB | 505.00 KiB/s
[0:03:38] Receiving objects:  97% (191260/196847), 103.47 MiB | 486.00 KiB/s
[0:03:40] Receiving objects:  97% (191262/196847), 104.10 MiB | 426.00 KiB/s
[0:03:41] Receiving objects:  97% (191263/196847), 104.97 MiB | 419.00 KiB/s
[0:03:43] Receiving objects:  97% (191263/196847), 105.47 MiB | 452.00 KiB/s
[0:03:44] Receiving objects:  97% (191264/196847), 106.16 MiB | 440.00 KiB/s
[0:03:46] Receiving objects:  97% (191267/196847), 107.22 MiB | 465.00 KiB/s
[0:03:48] Receiving objects:  97% (191268/196847), 107.66 MiB | 447.00 KiB/s
[0:03:49] Receiving objects:  97% (191269/196847), 108.41 MiB | 452.00 KiB/s
[0:03:51] Receiving objects:  97% (191274/196847), 109.34 MiB | 475.00 KiB/s
[0:03:52] Receiving objects:  97% (191275/196847), 109.97 MiB | 498.00 KiB/s
[0:03:54] Receiving objects:  97% (191275/196847), 110.91 MiB | 573.00 KiB/s
[0:03:55] Receiving objects:  97% (191275/196847), 111.84 MiB | 595.00 KiB/s
[0:03:56] Receiving objects:  97% (191275/196847), 112.47 MiB | 585.00 KiB/s
[0:03:58] Receiving objects:  97% (191275/196847), 113.09 MiB | 577.00 KiB/s
[0:03:59] Receiving objects:  97% (191275/196847), 113.53 MiB | 542.00 KiB/s
[0:04:00] Receiving objects:  97% (191276/196847), 114.40 MiB | 527.00 KiB/s
[0:04:01] Receiving objects:  97% (191276/196847), 114.90 MiB | 510.00 KiB/s
[0:04:02] Receiving objects:  97% (191276/196847), 115.47 MiB | 505.00 KiB/s
[0:04:03] Receiving objects:  97% (191276/196847), 116.09 MiB | 541.00 KiB/s
[0:04:04] Receiving objects:  97% (191276/196847), 116.72 MiB | 549.00 KiB/s
[0:04:06] Receiving objects:  97% (191276/196847), 117.34 MiB | 575.00 KiB/s
[0:04:07] Receiving objects:  97% (191276/196847), 117.97 MiB | 597.00 KiB/s
[0:04:08] Receiving objects:  97% (191276/196847), 118.78 MiB | 559.00 KiB/s
[0:04:09] Receiving objects:  97% (191276/196847), 119.40 MiB | 559.00 KiB/s
[0:04:10] Receiving objects:  97% (191276/196847), 120.03 MiB | 558.00 KiB/s
[0:04:12] Receiving objects:  97% (191276/196847), 120.65 MiB | 561.00 KiB/s
[0:04:13] Receiving objects:  97% (192381/196847), 121.59 MiB | 599.00 KiB/s
[0:04:14] Receiving objects:  97% (192382/196847), 122.21 MiB | 599.00 KiB/s
[0:04:15] Receiving objects:  97% (192382/196847), 122.84 MiB | 599.00 KiB/s
[0:04:16] Receiving objects:  97% (192382/196847), 123.46 MiB | 599.00 KiB/s
[0:04:18] Receiving objects:  98% (194292/196847), 124.40 MiB | 593.00 KiB/s
[0:04:19] Receiving objects:  99% (195320/196847), 124.90 MiB | 561.00 KiB/s
[0:04:20] Receiving objects:  99% (195847/196847), 125.53 MiB | 558.00 KiB/s
[0:04:21] Receiving objects:  99% (195849/196847), 125.90 MiB | 506.00 KiB/s
[0:04:22] Receiving objects:  99% (195855/196847), 126.40 MiB | 484.00 KiB/s
[0:04:24] Receiving objects:  99% (195860/196847), 127.34 MiB | 518.00 KiB/s
[0:04:26] Receiving objects:  99% (195861/196847), 128.28 MiB | 548.00 KiB/s
[0:04:27] Receiving objects:  99% (195862/196847), 128.90 MiB | 597.00 KiB/s
[0:04:28] Receiving objects:  99% (195863/196847), 129.84 MiB | 591.00 KiB/s
[0:04:30] Receiving objects:  99% (195864/196847), 130.84 MiB | 539.00 KiB/s
[0:04:31] Receiving objects:  99% (195865/196847), 131.46 MiB | 542.00 KiB/s
[0:04:33] Receiving objects:  99% (195867/196847), 132.40 MiB | 547.00 KiB/s
[0:04:35] Receiving objects:  99% (196468/196847), 133.65 MiB | 599.00 KiB/s
[0:04:36] Receiving objects:  99% (196468/196847), 134.27 MiB | 599.00 KiB/s
[0:04:37] Receiving objects:  99% (196771/196847), 134.87 MiB | 594.00 KiB/s
[0:04:38] Receiving objects:  99% (196771/196847), 135.27 MiB | 542.00 KiB/s
[0:04:40] Receiving objects:  99% (196771/196847), 135.90 MiB | 455.00 KiB/s
[0:04:41] Receiving objects:  99% (196771/196847), 136.46 MiB | 431.00 KiB/s
[0:04:44] Receiving objects:  99% (196772/196847), 137.65 MiB | 451.00 KiB/s
[0:04:45] Receiving objects:  99% (196772/196847), 138.27 MiB | 471.00 KiB/s
[0:04:47] Receiving objects:  99% (196772/196847), 138.83 MiB | 473.00 KiB/s
[0:04:48] Receiving objects:  99% (196772/196847), 139.77 MiB | 473.00 KiB/s
[0:04:50] Receiving objects:  99% (196772/196847), 140.40 MiB | 499.00 KiB/s
[0:04:51] Receiving objects:  99% (196772/196847), 141.15 MiB | 515.00 KiB/s
[0:04:52] remote: Total 196847 (delta 151858), reused 196802 (delta 151858)
[0:04:52] Receiving objects: 100% (196847/196847), 141.40 MiB | 496.00 KiB/s
[0:04:52] Resolving deltas:   0% (0/151858)
[0:04:53] Resolving deltas:  10% (15187/151858)
[0:04:54] Resolving deltas:  41% (62262/151858)
[0:04:55] Resolving deltas:  69% (104786/151858)
[0:04:56] Resolving deltas:  90% (136674/151858)
[0:04:56] Resolving deltas: 100% (151858/151858)
Traceback (most recent call last):
  File "C:\Users\Dave\Downloads\depot_tools\gclient_scm.py", line 911, in _Clone
    os.path.join(self.checkout_path, '.git'))
  File "C:\Users\Dave\Downloads\depot_tools\gclient_utils.py", line 169, in safe_rename
    os.rename(old, new)
WindowsError: [Error 5] Access is denied
[0:05:07] _____ removing non-empty tmp dir C:\Users\Dave\webrtc-checkout\_gclient_src_o4zufa
----------------------------------------
Traceback (most recent call last):
  File "C:\Users\Dave\Downloads\depot_tools\gclient.py", line 2129, in <module>
    sys.exit(main(sys.argv[1:]))
  File "C:\Users\Dave\Downloads\depot_tools\gclient.py", line 2115, in main
    return dispatcher.execute(OptionParser(), argv)
  File "C:\Users\Dave\Downloads\depot_tools\subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "C:\Users\Dave\Downloads\depot_tools\gclient.py", line 1877, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "C:\Users\Dave\Downloads\depot_tools\gclient.py", line 1364, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options)
  File "C:\Users\Dave\Downloads\depot_tools\gclient_utils.py", line 1048, in run
    self.item.run(*self.args, **self.kwargs)
  File "C:\Users\Dave\Downloads\depot_tools\gclient.py", line 773, in run
    file_list)
  File "C:\Users\Dave\Downloads\depot_tools\gclient_scm.py", line 156, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "C:\Users\Dave\Downloads\depot_tools\gclient_scm.py", line 438, in update
    self._Clone(revision, url, options)
  File "C:\Users\Dave\Downloads\depot_tools\gclient_scm.py", line 911, in _Clone
    os.path.join(self.checkout_path, '.git'))
  File "C:\Users\Dave\Downloads\depot_tools\gclient_utils.py", line 169, in safe_rename
    os.rename(old, new)
WindowsError: [Error 5] Access is denied
Traceback (most recent call last):
  File "C:\Users\Dave\Downloads\depot_tools\\fetch.py", line 300, in <module>
    sys.exit(main())
  File "C:\Users\Dave\Downloads\depot_tools\\fetch.py", line 295, in main
    return run(options, spec, root)
  File "C:\Users\Dave\Downloads\depot_tools\\fetch.py", line 289, in run
    return checkout.init()
  File "C:\Users\Dave\Downloads\depot_tools\\fetch.py", line 132, in init
    self.run_gclient(*sync_cmd)
  File "C:\Users\Dave\Downloads\depot_tools\\fetch.py", line 76, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "C:\Users\Dave\Downloads\depot_tools\\fetch.py", line 66, in run
    return subprocess.check_output(cmd, **kwargs)
  File "C:\Users\Dave\Downloads\depot_tools\python276_bin\lib\subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('C:\\Users\\Dave\\Downloads\\depot_tools\\python276_bin\\python.exe', 'C:\\Users\\Dave\\Downloads\\depot_tools\\gclient
.py', 'sync', '--nohooks', '--with_branch_heads')' returned non-zero exit status 1


```C:\Users\Dave\webrtc-checkout>

**Comment by daveime** [comment]
Update for anyone enduring the same frustration as myself.

Run as Administrator. Disable the Windows Search service. Disable antivirus. And finally, close ALL File Explorer windows or anything observing the filesystem. Apparently even having a folder open in File Explorer is enough to lock the filesystem as far as Python is concerned? 

Finally took and completed without any errors.
