### ISSUE TITLE
Import KeyRing Scope Problem

### ISSUE THREAD

**Issue by vahid-dan** [ipop-project/ipop-project.github.io#29]
Whenever KeyRing module is installed, after running the Controller, it throws an error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/vd/Downloads/ipop-rel17.08-ubuntu/controller/Controller.py", line 55, in <module>
    main()
  File "/home/vd/Downloads/ipop-rel17.08-ubuntu/controller/Controller.py", line 50, in main
    cfx.initialize()
  File "controller/framework/CFx.py", line 82, in initialize
    self.load_module(key)
  File "controller/framework/CFx.py", line 126, in load_module
    handle.initialize()
  File "controller/framework/CFxHandle.py", line 65, in initialize
    self.CMInstance.initialize()
  File "controller/modules/XmppClient.py", line 315, in initialize
    xmpp_password = keyring.get_password("ipop", xmpp_ele['Username'])
NameError: global name 'keyring' is not defined
```
The problem is with the scope of `keyring` global name. A quich fix would be to import keyring at the top of `controller/modules/XmppClient.py`.

**Comment by vahid-dan** [comment]
It got fixed in the new release.
