### ISSUE TITLE
ubuntu latest version: ile "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main     "__main__", mod_spec)

### ISSUE THREAD

**Issue by gurussia** [ipop-project/ipop-project.github.io#62]
Hi guys.

It don't work in ubuntu latest versions:

When it was followed this tutorial: https://github.com/ipop-project/ipop-project.github.io/wiki/Use-IPOP-on-Ubuntu-and-Raspberry-Pi,-Manually

It comment this error:

python3 -m controller.Controller -c ./config/gvpn-config.json &
[2] 31529
 pe@ pe:/etc/ejabberd/ipop# Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/etc/ejabberd/ipop/controller/Controller.py", line 55, in <module>
    main()
  File "/etc/ejabberd/ipop/controller/Controller.py", line 49, in main
    cfx = CFX()
  File "/etc/ejabberd/ipop/controller/framework/CFx.py", line 42, in __init__
    self.parse_config()
  File "/etc/ejabberd/ipop/controller/framework/CFx.py", line 181, in parse_config
    self.json_data = json.load(f, object_pairs_hook=OrderedDict)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
^C
[2]+  Exit 1                  python3 -m controller.Controller -c ./config/gvpn-config.json
 pe@ pe:/etc/ejabberd/ipop# fg
sudo -u zagitlab ./ipop-tincan
^C

It comment python3 becouse we try python 2 and it comment other error. So with python2 or python3 

ipop-project.github.io is not working. Tutorial is error.

**Comment by gurussia** [comment]
We just remember. We want to implement xmpp ejabberd server with ipop:

https://github.com/ipop-project/Legacy-Documentation/wiki/Running-GroupVPN-on-Linux

Someone comment how to do it.
